import type { AppState, Engagement, EngagementStatus, Goal, Operation, Strategy } from '../types';

const STATUS_LABELS: Record<string, string> = {
  active: 'Active',
  blocked: 'Blocked',
  completed: 'Completed',
};

// Reverse map: display label → EngagementStatus
const LABEL_TO_STATUS: Record<string, EngagementStatus> = {
  active: 'active',
  Active: 'active',
  blocked: 'blocked',
  Blocked: 'blocked',
  completed: 'completed',
  Completed: 'completed',
};

const STRATEGY_COLORS = [
  '#4a90d9', '#7b68ee', '#50c878', '#ff6b6b', '#ffa500',
  '#20b2aa', '#da70d6', '#87ceeb',
];

function uid(): string {
  return Math.random().toString(36).slice(2, 10);
}

// Escape backslashes and pipe characters inside a table cell so the table
// remains parseable and round-trips losslessly.
function escapeCell(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

// Unescape any `\X` sequence back to `X` (handles `\|` → `|` and `\\` → `\`).
function unescapeCell(s: string): string {
  return s.replace(/\\(.)/g, '$1');
}

function engagementsForOperation(
  op: Operation,
  state: AppState,
): Engagement[] {
  return op.engagementIds
    .map(id => state.engagements[id])
    .filter(Boolean);
}

function operationBlock(op: Operation, state: AppState): string {
  const engagements = engagementsForOperation(op, state);
  const total = engagements.length;
  const counts = { active: 0, blocked: 0, completed: 0 };
  for (const e of engagements) {
    counts[e.status] = (counts[e.status] ?? 0) + 1;
  }

  const lines: string[] = [];
  lines.push(`### Operation: ${op.title}`);
  lines.push('');
  lines.push(
    `**Status**: ${counts.active} active, ${counts.blocked} blocked, ${counts.completed} completed (${total} total)`,
  );
  lines.push('');

  if (op.goals.length > 0) {
    lines.push('#### Goals');
    lines.push('');
    for (const g of op.goals) {
      lines.push(`- ${g.description}`);
    }
    lines.push('');
  }

  if (engagements.length > 0) {
    lines.push('#### Engagements');
    lines.push('');
    lines.push('| Title | Status | Goal Targets | Description |');
    lines.push('|-------|--------|--------------|-------------|');
    for (const e of engagements) {
      const goalNames = e.goalTargetIds
        .map(gid => op.goals.find(g => g.id === gid)?.description ?? gid)
        .join(', ');
      const status = STATUS_LABELS[e.status] ?? e.status;
      lines.push(
        `| ${escapeCell(e.title)} | ${status} | ${escapeCell(goalNames)} | ${escapeCell(e.description)} |`,
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

function strategyBlock(strategy: Strategy, state: AppState): string {
  const lines: string[] = [];
  lines.push(`## Strategy: ${strategy.name}`);
  lines.push('');

  for (const opId of strategy.operationIds) {
    const op = state.operations[opId];
    if (op) {
      lines.push(operationBlock(op, state));
    }
  }

  return lines.join('\n');
}

export function generateMarkdown(state: AppState): string {
  const lines: string[] = [];
  lines.push('# Workstream Tracker');
  lines.push('');
  lines.push(`_Generated: ${new Date().toISOString()}_`);
  lines.push('');

  for (const stratId of state.strategyOrder) {
    const strategy = state.strategies[stratId];
    if (strategy) {
      lines.push(strategyBlock(strategy, state));
    }
  }

  return lines.join('\n');
}

export function downloadMarkdown(state: AppState): void {
  const md = generateMarkdown(state);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'workstream-tracker.md';
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Parse a markdown document previously generated by `generateMarkdown` back
 * into an `AppState`.  Returns `null` when the text contains no recognisable
 * strategies (i.e. the file is not a workstream-tracker export).
 */
export function parseMarkdown(text: string): AppState | null {
  const result: AppState = {
    strategies: {},
    operations: {},
    engagements: {},
    strategyOrder: [],
  };

  let colorIdx = 0;
  let currentStrategyId: string | null = null;
  let currentOperationId: string | null = null;
  type Section = 'root' | 'strategy' | 'operation' | 'goals' | 'engagements';
  let section: Section = 'root';

  for (const rawLine of text.split('\n')) {
    const line = rawLine.trimEnd();

    // ── Headings are always processed first so they can break out of any
    //    active section (goals / engagements lists stop at the next heading).

    // ## Strategy: <name>
    const stratMatch = line.match(/^## Strategy: (.+)$/);
    if (stratMatch) {
      const id = uid();
      const strategy: Strategy = {
        id,
        name: stratMatch[1].trim(),
        color: STRATEGY_COLORS[colorIdx++ % STRATEGY_COLORS.length],
        operationIds: [],
      };
      result.strategies[id] = strategy;
      result.strategyOrder.push(id);
      currentStrategyId = id;
      currentOperationId = null;
      section = 'strategy';
      continue;
    }

    // ### Operation: <title>
    const opMatch = line.match(/^### Operation: (.+)$/);
    if (opMatch && currentStrategyId) {
      const id = uid();
      const op: Operation = {
        id,
        title: opMatch[1].trim(),
        strategyId: currentStrategyId,
        goals: [],
        engagementIds: [],
      };
      result.operations[id] = op;
      result.strategies[currentStrategyId].operationIds.push(id);
      currentOperationId = id;
      section = 'operation';
      continue;
    }

    // #### Goals
    if (line === '#### Goals' && currentOperationId) {
      section = 'goals';
      continue;
    }

    // #### Engagements
    if (line === '#### Engagements' && currentOperationId) {
      section = 'engagements';
      continue;
    }

    // Any other H2–H4 heading resets to the outer section
    if (line.match(/^#{2,4} /)) {
      section = currentOperationId ? 'operation' : currentStrategyId ? 'strategy' : 'root';
      continue;
    }

    // ── Section content ──────────────────────────────────────────────────────

    if (section === 'goals' && currentOperationId) {
      const goalMatch = line.match(/^- (.+)$/);
      if (goalMatch) {
        const goal: Goal = { id: uid(), description: goalMatch[1].trim() };
        result.operations[currentOperationId].goals.push(goal);
      }
      continue;
    }

    if (section === 'engagements' && currentOperationId) {
      // Skip blank lines, the header row and the separator row
      if (line.trim() === '') continue;
      if (/^\|[-| ]+\|$/.test(line)) continue;          // separator
      if (/^\| Title\s*\|/i.test(line)) continue;        // header

      if (line.startsWith('|')) {
        // Split on unescaped `|` — slice away the leading/trailing empty strings
        const cells = line.split('|').slice(1, -1).map(c => c.trim());
        if (cells.length < 4) continue;

        const op = result.operations[currentOperationId];
        const title = unescapeCell(cells[0]);
        const statusLabel = cells[1];
        const goalTargetsStr = unescapeCell(cells[2]);
        // Everything from index 3 onwards belongs to description (handles
        // any unescaped pipes that were already in the source data)
        const description = unescapeCell(cells.slice(3).join(' | '));

        const goalNames = goalTargetsStr
          ? goalTargetsStr.split(',').map(s => s.trim()).filter(Boolean)
          : [];
        const goalTargetIds = goalNames
          .map(name => op.goals.find(g => g.description === name)?.id)
          .filter((id): id is string => id !== undefined);

        const status: EngagementStatus = LABEL_TO_STATUS[statusLabel] ?? 'active';

        const id = uid();
        const eng: Engagement = {
          id,
          title,
          description,
          status,
          goalTargetIds,
          operationId: currentOperationId,
        };
        result.engagements[id] = eng;
        op.engagementIds.push(id);
      }
      continue;
    }
  }

  return result.strategyOrder.length > 0 ? result : null;
}
